In [ ]:

!pip install opendatasets --upgrade --quiet
import pandas as pd
import os
import opendatasets as od

In [ ]:
# Assign the Kaggle data set URL into variable
dataset = 'https://www.kaggle.com/datasets/prepinstaprime/tomato-reviews'
# Using opendatasets let's download the data sets
od.download(dataset , force=True)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: jay1239
Your Kaggle Key: ··········
Downloading tomato-reviews.zip to ./tomato-reviews

100%|██████████| 89.0M/89.0M [00:00<00:00, 112MB/s]

In [ ]:
data_dir = './tomato-reviews'
print(os.listdir(data_dir))

['zomato.csv']

In [ ]:
data_dir = './tomato-reviews/zomato.csv'
zmt=pd.read_csv(data_dir)

In [ ]:
zmt.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
zmt.info() #checking information of our dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [ ]:
zmt.drop(['url','reviews_list','menu_item','address','phone','dish_liked'],axis=1,inplace=True)

In [ ]:
zmt.head(2)

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari

In [ ]:
zmt.rename(columns={'name':'restaurants','rate':'rating','cuisines':'food_type','listed_in(type)':'type','listed_in(city)':'city','approx_cost(for two people)':'cost'},inplace=True)

In [ ]:
zmt.dropna(inplace = True) # Droping NaN values for better result using dropna()

In [ ]:
zmt.groupby('restaurants').count().head() # we are grouping the restaurants to see the restaurant names and their count.

,online_order,book_table,rating,votes,location,rest_type,food_type,cost,type,city
restaurants,,,,,,,,,,
#FeelTheROLL,2,2,2,2,2,2,2,2,2,2
#L-81 Cafe,9,9,9,9,9,9,9,9,9,9
#refuel,3,3,3,3,3,3,3,3,3,3
1000 B.C,6,6,6,6,6,6,6,6,6,6
100ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°C,3,3,3,3,3,3,3,3,3,3

In [ ]:
# '[Ãx][^A-Za-z]+' pattern I got to find disturbed characters using regex.And Replacing those charachters with empty space.
zmt['restaurants']=zmt['restaurants'].str.replace('[Ãx][^A-Za-z]+','',regex=True)

In [ ]:
zmt.groupby('restaurants').count().head()

,online_order,book_table,rating,votes,location,rest_type,food_type,cost,type,city
restaurants,,,,,,,,,,
#FeelTheROLL,2,2,2,2,2,2,2,2,2,2
#L-81 Cafe,9,9,9,9,9,9,9,9,9,9
#refuel,3,3,3,3,3,3,3,3,3,3
1000 B.C,6,6,6,6,6,6,6,6,6,6
100C,3,3,3,3,3,3,3,3,3,3

In [ ]:
zmt['restaurants']=zmt['restaurants'].str.replace('Caf-|Caf ','Cafe ',regex=True) # replacing the Caf- or Caf names with cafe using pattern matching

In [ ]:
zmt['online_order'].unique() # Using .unique() we can find the unique values from column

array(['Yes', 'No'], dtype=object)

In [ ]:
zmt['book_table'].unique()
zmt['rating'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '-', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [ ]:
replace=lambda x:x.replace('/5',"") # lambda function to replace /5 to empty string
l=[] # list to store cleaned values
for val in map(replace, zmt['rating']): # map function to read data from column and replace /5 to empty string
    if val!='NEW' and val!='-':  # excluding 'NEW' and '-' values
        var=float(val) # converting the result in float datatype and storing into one variable
    l.append(var) # appendin  values in created list
zmt['rating'].replace('/5' , "" , inplace = 'True')

ValueError: For argument "inplace" expected type bool, received type str.

In [ ]:
zmt['rating'].unique(),zmt['rating'].dtype

In [ ]:
zmt['votes'].isnull().value_counts()

In [ ]:
zmt.location.unique(), zmt.rest_type.unique(), zmt.rest_type.isnull().value_counts()

In [ ]:
zmt.rest_type.unique(), zmt.rest_type.isnull().value_counts()

In [ ]:
zmt.cost.unique()

In [ ]:
zmt['cost']= zmt['cost'].apply(lambda x:x.replace(",","")).astype(int) # we can also apply lambda function using .apply()

In [ ]:
zmt.type.unique()

In [ ]:
zmt.city.unique()

In [ ]:
zmt.duplicated().value_counts()

In [ ]:
zmt.drop_duplicates(keep='last',inplace=True)# dropping duplicates values using .drop_duplicates()
zmt.reset_index(drop=True,inplace=True) # reseting index

In [ ]:
zmt.duplicated().value_counts()

In [ ]:
zmt

In [ ]:
zmt.info()

In [ ]:
zmt.to_csv('./zomato_clean_data.csv')

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
zmt.head(1)

In [ ]:
plt.figure(figsize=(10,5))
sns.countplot(x='online_order',data=zmt) # countplot gives us count of the values
plt.show()

In [ ]:
plt.figure(figsize=(16,10)) # seeting graph size using matplotlib
ax = plt.subplot(2,1,1)   # use of Subploting
loc_rating=zmt.groupby('location').agg({'rating':'median'})
rating_sorted_loc=loc_rating.sort_values('rating',ascending=False).head(5).reset_index() # sorting location on avg of votes in descending order and reading first 5 values
sns.barplot(x='location',y='rating',data=rating_sorted_loc) # ploting graph using seaborn

ax = plt.subplot(2,1,2)
loc_votes=zmt.groupby('location').agg({'votes':'median'})
votes_sorted_loc=loc_votes.sort_values('votes',ascending=False).head(5).reset_index() # sorting location on avg of rating in descending order and reading first 5 values
sns.barplot(x='location',y='votes',
            data=votes_sorted_loc)
plt.show()

In [ ]:
zmt.head(1)

In [ ]:
plt.figure(figsize=(10,20))
rest_types=zmt.groupby('rest_type')['restaurants'].count().reset_index()# grouping restaurants types and getting 'restaurant' count
sorted_rest_types=rest_types.sort_values('restaurants',ascending=False).head(40) # sorting restaurant types on 'restaurants' counts in descending order and reading 40 values
rest_types.rest_type.count(),sns.barplot(x='restaurants',y='rest_type',data=sorted_rest_types,orient='h')# drawing horizontal bar plot to see results

In [ ]:
zmt.head(1)

In [ ]:
 zmt.head(1)

In [ ]:
zmt.info()

In [ ]:
plt.figure(figsize=(10,5))
sns.kdeplot(x='cost',data= zmt, )# KDE plot
plt.show()

In [ ]:
plt.figure(figsize=(10,5))
table_booking= zmt.groupby('book_table')['restaurants'].count().reset_index()
sns.pointplot(x='book_table',y='restaurants',color='b',data=table_booking)
plt.show()

In [ ]:
df=pd.DataFrame(zmt.groupby('location')['restaurants'].count()).reset_index()
criteria=df['location'].isin(['BTM','Basavanagudi','West Bangalore','Whitefield','Yeshwantpur']) # selecting given locations from dataset using isin()
plt.figure(figsize=(10,5))
sns.barplot(x='location',y='restaurants',data=df[criteria])
plt.show()

In [ ]:
df1=pd.DataFrame(zmt.groupby(['location','restaurants','rating']).count()).reset_index() # getting location,restraunts and rating and their count of restaurants
df1

In [ ]:
sns.distplot(df1['cost'])

In [ ]:
chains_restaurants=df1[(df1['book_table']>1)]
famous_restaurants=pd.DataFrame(chains_restaurants.groupby('location')['restaurants','rating'].max()).reset_index()
famous_restaurants

In [ ]:
sns.catplot(x="location", y="rating", hue="restaurants",kind='bar',height=7,data=famous_restaurants.head(5))

In [ ]:
df2=zmt.groupby('type').agg({'votes':'sum','rating':'mean'}).nlargest(7,['votes']).reset_index()
sns.catplot(x='type',y='rating',hue='votes',kind='bar',height=8,data=df2)
plt.show()

In [ ]:
sns.distplot(zmt['rating'])

In [ ]:
Chinese=len([i for i in zmt['food_type'] if 'Chinese' in i]) # count of restaurants who serving chinese food.
North_India=len([i for i in zmt['food_type'] if 'North India' in i]) # count of restaurants who serving North Indian food.
Restaurant_count=[Chinese,North_India] #creating list
Food_Type=['Chinese','North India']
df3 = pd.DataFrame({'Food_Type':Food_Type,'Restaurant_count':Restaurant_count})#.set_index('Food_Type')# creating dataset of extracted data

In [ ]:
sns.barplot(x='Food_Type',y='Restaurant_count',data=df3) # countplot gives us count of the values
plt.show()

In [ ]:
df4=zmt.groupby('type').agg({'cost':'mean'})
df4.cost.plot(kind='pie',autopct='%1.1f%%',figsize=(9,9),shadow=True)
plt.show()